x-app: &default-app
  volumes:
    - ${BACKUP_DIR:?}:/backups
  depends_on:
    - postgres
  env_file:
    - .env
  environment:
    DATABASE_URL: postgres://postgres:postgres@postgres.local:5432/postgres
    DBBACKUP_STORAGE_LOCATION: /backups
    IS_DOCKER_CONTAINER: 1

services:
  # We have to to define the init servce in base (even if we don't use it
  # in development) to set the correct environment variables.
  init:
    <<: *default-app
    hostname: init.local

  web:
    <<: *default-app
    build:
      args:
        - PROJECT_VERSION=${PROJECT_VERSION:?}
    hostname: web.local

  worker:
    <<: *default-app
    hostname: worker.local

  postgres:
    image: postgres:17@sha256:e38411452a464af89e5adadb8d223bf53b898d47d6ef918b2d58c08707350449
    hostname: postgres.local
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
