x-app: &default-app
  volumes:
    - ${BACKUP_DIR:?}:/backups
  depends_on:
    - postgres
  environment:
    BACKUP_DIR: ${BACKUP_DIR:?}
    DATABASE_URL: postgres://postgres:postgres@postgres.local:5432/postgres
    DBBACKUP_STORAGE_LOCATION: /backups
    DJANGO_ADMIN_EMAIL: ${DJANGO_ADMIN_EMAIL:?}
    DJANGO_ADMIN_FULL_NAME: ${DJANGO_ADMIN_FULL_NAME:?}
    DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS:?}
    DJANGO_CSRF_TRUSTED_ORIGINS: ${DJANGO_CSRF_TRUSTED_ORIGINS:-}
    DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY:?}
    DJANGO_SERVER_EMAIL: ${DJANGO_SERVER_EMAIL:?}
    IS_DOCKER_CONTAINER: 1
    SITE_DOMAIN: ${SITE_DOMAIN:?}
    SITE_NAME: ${SITE_NAME:?}
    SUPERUSER_AUTH_TOKEN: ${SUPERUSER_AUTH_TOKEN:-}
    SUPERUSER_EMAIL: ${SUPERUSER_EMAIL:-}
    SUPERUSER_USERNAME: ${SUPERUSER_USERNAME:-}
    SUPERUSER_PASSWORD: ${SUPERUSER_PASSWORD:-}
    SUPPORT_EMAIL: ${SUPPORT_EMAIL:?}
    TOKEN_AUTHENTICATION_SALT: ${TOKEN_AUTHENTICATION_SALT:?}
    USER_TIME_ZONE: ${USER_TIME_ZONE:?}

services:
  # We have to to define the init servce in base (even if we don't use it
  # in development) to set the correct environment variables.
  init:
    <<: *default-app
    hostname: init.local

  web:
    <<: *default-app
    hostname: web.local

  worker:
    <<: *default-app
    hostname: worker.local

  postgres:
    image: postgres:latest
    hostname: postgres.local
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
