x-app: &default-app
  volumes:
    - web_data:/var/www/web
    - ${BACKUP_DIR:?BACKUP_DIR must be set}:/backups
  depends_on:
    - postgres
  user: ${SERVICE_UID:?SERVICE_UID must be set}:${SERVICE_GID:-${SERVICE_UID}}
  environment:
    ADMIN_AUTH_TOKEN: ${ADMIN_AUTH_TOKEN}
    ADMIN_EMAIL: ${ADMIN_EMAIL}
    ADMIN_USERNAME: ${ADMIN_USERNAME}
    ADMIN_PASSWORD: ${ADMIN_PASSWORD}
    BACKUP_DIR: ${BACKUP_DIR:?BACKUP_DIR must be set}
    DATABASE_URL: "psql://postgres:postgres@postgres.local:5432/postgres"
    DJANGO_ADMIN_EMAIL: ${DJANGO_ADMIN_EMAIL:?DJANGO_ADMIN_EMAIL must be set}
    DJANGO_ADMIN_FULL_NAME: ${DJANGO_ADMIN_FULL_NAME:?DJANGO_ADMIN_FULL_NAME must be set}
    DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS:?DJANGO_ALLOWED_HOSTS must be set}
    DJANGO_CSRF_TRUSTED_ORIGINS: ${DJANGO_CSRF_TRUSTED_ORIGINS:?DJANGO_CSRF_TRUSTED_ORIGINS must be set}
    DJANGO_INTERNAL_IPS: ${DJANGO_INTERNAL_IPS:?DJANGO_INTERNAL_IPS must be set}
    DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY:?DJANGO_SECRET_KEY must be set}
    DJANGO_SERVER_EMAIL: ${DJANGO_SERVER_EMAIL:?DJANGO_SERVER_EMAIL must be set}
    DJANGO_STATIC_ROOT: "/var/www/web/static/"
    PROJECT_VERSION: ${PROJECT_VERSION:-vX.Y.Z}
    SITE_DOMAIN: ${SITE_DOMAIN:?SITE_DOMAIN must be set}
    SITE_NAME: ${SITE_NAME:?SITE_NAME must be set}
    SITE_USES_HTTPS: ${SITE_USES_HTTPS:-false}
    SUPPORT_EMAIL: ${SUPPORT_EMAIL:?SUPPORT_EMAIL must be set}
    TOKEN_AUTHENTICATION_SALT: ${TOKEN_AUTHENTICATION_SALT:?TOKEN_AUTHENTICATION_SALT must be set}
    USE_DOCKER: true
    USER_TIME_ZONE: ${USER_TIME_ZONE:?USER_TIME_ZONE must be set}

services:
  # We have to to define the init servce in base (even if we don't use it
  # in development) to set the correct environment variables.
  init:
    <<: *default-app
    hostname: init.local

  web:
    <<: *default-app
    hostname: web.local

  worker:
    <<: *default-app
    hostname: worker.local

  postgres:
    image: postgres:latest
    hostname: postgres.local
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  web_data:
  postgres_data:
