# Generated by Django 5.0.6 on 2024-06-17 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_alter_user_active_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="department",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
