# Generated by Django 5.0.4 on 2024-05-25 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_update_or_create_site'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteprofile',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='siteprofile',
            name='meta_keywords',
        ),
        migrations.RemoveField(
            model_name='siteprofile',
            name='project_url',
        ),
        migrations.RemoveField(
            model_name='siteprofile',
            name='site',
        ),
    ]
