# Generated by Django 5.1 on 2024-10-03 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_projectsettings_delete_siteprofile'),
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uses_https', models.BooleanField(default=False)),
                ('meta_keywords', models.CharField(blank=True, max_length=120)),
                ('meta_description', models.TextField(blank=True, max_length=200)),
                ('project_url', models.URLField(blank=True)),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='sites.site')),
            ],
        ),
    ]
