# Generated by Django 5.0.4 on 2024-05-25 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_remove_unneeded_siteprofile_fields'),
        # ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SiteProfile',
            new_name='ProjectSettings',
        ),
    ]
