# Generated by Django 5.1.4 on 2025-01-16 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0004_siteprofile"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SiteProfile",
        ),
    ]
